xml.instruct!(:xml, :encoding => "UTF-8", version: "1.0")
xml.urlset(xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9", 'xmlns:xsi'=>"http://www.w3.org/2001/XMLSchema-instance", 'xsi:schemaLocation' => "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"){
  xml.url{
    xml.loc("#{root_url}")
    xml.lastmod(1.day.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('1.0')
  }
  xml.url{
    xml.loc("#{page_abouts_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('0.9')
  }
  @about_sections.each do |page|
    xml.url{
      xml.loc("#{page_about_url(page.path)}")
      xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
      xml.changefreq('daily')
      xml.priority('0.8')
    }
  end
  xml.url{
    xml.loc("#{page_partners_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('0.9')
  }
  xml.url{
    xml.loc("#{page_team_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('0.9')
  }
  xml.url{
    xml.loc("#{page_projects_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('1.0')
  }
  xml.url{
    xml.loc("#{page_exhibits_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('weekly')
    xml.priority('0.8')
  }
  xml.url{
    xml.loc("#{page_contact_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('weekly')
    xml.priority('0.8')
  }
  xml.url{
    xml.loc("#{page_press_url}")
    xml.lastmod(1.week.ago.strftime("%Y-%m-%d"))
    xml.changefreq('daily')
    xml.priority('0.9')
  }
}
