# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77054a79b9aa7e5e45fa88a5168e83869352746d9e82d3cdc84dbaad6f997bf8594e067c85d4a605562f7869476a66e00d1f34df0b2cde3dc05197ddd041d88d
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  amazon_secret_key: <%= ENV['AMAZON_SECRET_KEY'] %>
  amazon_s3_bucket: <%= ENV['AMAZON_S3_BUCKET'] %>

test:
  secret_key_base: b3ca27ef0be79288d38b51bb3cf9c0e5eee56196ba4a4003e972e4a4dc5086da1b34327eff2bd4f5e7a638ea7977a44a647562cded1b65a4f495a7a6f6926ede
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  amazon_secret_key: <%= ENV['AMAZON_SECRET_KEY'] %>
  amazon_s3_bucket: <%= ENV['AMAZON_S3_BUCKET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  amazon_secret_key: <%= ENV['AMAZON_SECRET_KEY'] %>
  amazon_s3_bucket: <%= ENV['AMAZON_S3_BUCKET'] %>
  cdn_host: <%= ENV['CDN_HOST'] %>
